'welcom to naresh i technology'

# PYTORCH INSTALLATION IN CPU

In [10]:
#!pip install torch

'#pip' is not recognized as an internal or external command,
operable program or batch file.


In [1]:
import torch 

In [2]:
torch.__version__

'2.2.1+cu118'

In [3]:
torch.cuda.is_available()

False

In [6]:
x = torch.rand(1,2)
x

tensor([[0.5485, 0.5262]])

In [7]:
x1 = torch.rand(2,3)
x1

tensor([[0.7553, 0.2276, 0.2024],
        [0.2779, 0.3211, 0.8170]])

In [8]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.3994, 0.7209, 0.7224],
        [0.1273, 0.2067, 0.4790],
        [0.5288, 0.2499, 0.1464],
        [0.0117, 0.8175, 0.5759],
        [0.6346, 0.0099, 0.2022]])


In [ ]:
torch.zeros(3) 

tensor([0., 0., 0.])

In [10]:
torch.zeros([3,3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.zeros([2,4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [12]:
x2= torch.tensor([[1,2,3],[4,5,6]])
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x2[0][1] = 8

In [14]:
x2

tensor([[1, 8, 3],
        [4, 5, 6]])

In [15]:
x

tensor([[0.3994, 0.7209, 0.7224],
        [0.1273, 0.2067, 0.4790],
        [0.5288, 0.2499, 0.1464],
        [0.0117, 0.8175, 0.5759],
        [0.6346, 0.0099, 0.2022]])

In [16]:
x1

tensor([[0.7553, 0.2276, 0.2024],
        [0.2779, 0.3211, 0.8170]])

In [17]:
x2

tensor([[1, 8, 3],
        [4, 5, 6]])

In [18]:
list = [1,2,3]
list

[1, 2, 3]

In [19]:
print(type(list))

<class 'list'>


In [20]:
import numpy as np
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [21]:
te = torch.tensor([10,20,30,40])
te

tensor([10, 20, 30, 40])

In [44]:
te.dtype

torch.int64

In [22]:
n1.dtype

dtype('int32')